# Generated by Django 5.0.3 on 2024-04-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statistics',
            name='km_totals_constraint',
        ),
    ]
