# Generated by Django 5.0.3 on 2024-03-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_default_value_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('adreca', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bicing',
            name='adreca',
        ),
        migrations.RemoveField(
            model_name='bicing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bicing',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='bicing',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='bicing',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='bicing',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='adreca',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='fgc',
            name='adreca',
        ),
        migrations.RemoveField(
            model_name='fgc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fgc',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='fgc',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='fgc',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='fgc',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='adreca',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='puntsrecarrega',
            name='adreca',
        ),
        migrations.RemoveField(
            model_name='puntsrecarrega',
            name='id',
        ),
        migrations.RemoveField(
            model_name='puntsrecarrega',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='puntsrecarrega',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='puntsrecarrega',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='puntsrecarrega',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='renfe',
            name='adreca',
        ),
        migrations.RemoveField(
            model_name='renfe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='renfe',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='renfe',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='renfe',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='renfe',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tram',
            name='adreca',
        ),
        migrations.RemoveField(
            model_name='tram',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tram',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='tram',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='tram',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='tram',
            name='rating',
        ),
        migrations.AlterField(
            model_name='bicing',
            name='capacitat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puntsrecarrega',
            name='potencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bicing',
            name='estacio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='estacio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fgc',
            name='estacio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metro',
            name='estacio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntsrecarrega',
            name='estacio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renfe',
            name='estacio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tram',
            name='estacio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio'),
            preserve_default=False,
        ),
    ]
