# Generated by Django 5.0.3 on 2024-03-11 15:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_estacio_tables_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacioBus',
            fields=[
                ('estacio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio')),
                ('linies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
            ],
            bases=('api.estacio',),
        ),
        migrations.CreateModel(
            name='EstacioTransportPublic',
            fields=[
                ('estacio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.estacio')),
            ],
            bases=('api.estacio',),
        ),
        migrations.CreateModel(
            name='TipusTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('METRO', 'metro'), ('TRAM', 'tram'), ('FGC', 'fgc'), ('RENFE', 'renfe')], max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bicing',
            new_name='EstacioBicing',
        ),
        migrations.RemoveField(
            model_name='fgc',
            name='estacio_ptr',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='estacio_ptr',
        ),
        migrations.RemoveField(
            model_name='renfe',
            name='estacio_ptr',
        ),
        migrations.RemoveField(
            model_name='tram',
            name='estacio_ptr',
        ),
        migrations.RemoveField(
            model_name='estacio',
            name='adreca',
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linia', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None)),
                ('estacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estaciotransportpublic')),
                ('tipus_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipustransport')),
            ],
        ),
        migrations.DeleteModel(
            name='BUS',
        ),
        migrations.DeleteModel(
            name='FGC',
        ),
        migrations.DeleteModel(
            name='Metro',
        ),
        migrations.DeleteModel(
            name='RENFE',
        ),
        migrations.DeleteModel(
            name='Tram',
        ),
    ]
