# Generated by Django 5.0.3 on 2024-03-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_db_restructure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parada',
            old_name='linia',
            new_name='linies',
        ),
    ]
